### ISSUE TITLE
Units are missing in nutrient levels

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#196]
![image](https://user-images.githubusercontent.com/1689815/53627551-03584700-3c09-11e9-841c-cd49a30ce4f4.png)
It happens on the summary tab and on the nutrition tab

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/59716030-6b14bb00-9215-11e9-95a2-e1c8b7a48c1d.png)
Still here in latest Testflight

**Comment by aleene** [comment]
Is solved

**Comment by davidlamys** [comment]
hi @aleene, I was just trying to figure out how to solve this since it felt like a good starter issue >.<

Any chance you can reference the commit / PR that helped to fix this? It could help accelerate newbies like me.

Thank you :)

**Comment by aleene** [comment]
I am afraid I just closed this issue a few days ago. It was already resolved. 

A simple start project could be #386

**Comment by teolemon** [comment]
It's not solved
![image](https://user-images.githubusercontent.com/1689815/91227497-e5e53a00-e726-11ea-9134-1e30bbc1ada7.png)

**Comment by teolemon** [comment]
https://barcode.tec-it.com/fr/EAN13?data=3560070100484
